stages:
  train:
    cmd: make docker-train
    deps:
    - ml/input/data/training/creditcard.csv
    - ml/input/config/hyperparameters.json
    - src/experiment
    - src/train
    - src/utils
    - Makefile
    - Pipfile
    - Pipfile.lock
    outs:
    - ml/output/credit-card-fraud/confusion-matrix.png:
        cache: false
    - ml/output/credit-card-fraud/model.joblib:
        cache: false
    - ml/output/credit-card-fraud/precision-recall-curve.png:
        cache: false
    - ml/output/model.tar.gz
    metrics:
    - ml/output/credit-card-fraud/metrics.txt
