stages:
  get-data:
    cmd: kaggle datasets download mlg-ulb/creditcardfraud --unzip --path ml/input/data/training
    outs:
    - ml/input/data/training/creditcard.csv
  train:
    cmd: make docker-train
    deps:
    - ml/input/data/training/creditcard.csv
    - src/experiment
    - src/train
    - src/utils
    - Makefile
    - Dockerfile
    - Pipfile
    outs:
    - ml/output/credit-card-fraud/confusion-matrix.png:
        cache: false
    - ml/output/credit-card-fraud/model.joblib:
        cache: false
    - ml/output/credit-card-fraud/precision-recall-curve.png:
        cache: false
    - ml/output/model.tar.gz
    metrics:
    - ml/output/credit-card-fraud/metrics.txt