version: '3.8'
services:
  
  batch-request:
    depends_on: 
      - credit-fraud-api
    image: nyurik/alpine-python3-requests
    networks:
      - test
    volumes:
      - "../../ml/input/api:/opt"
      - ".:/opt/output"
    restart: always
    links:
      - credit-fraud-api
    command: ./opt/output/request.py

  credit-fraud-api:
    image: 'credit-fraud-ml'
    networks:
      - test
    volumes:
      - "../../ml:/opt/ml"
    expose:
      - "8080"
    restart: always
    healthcheck:
      test: "curl -f credit-fraud-api/ping || false"
      timeout: 10s
      retries: 3
    command: serve

networks:
  test:

volumes:
  .: